package u8.ej4;public enum provincias {
    JUJUY, SALTA, MISIONES, FORMOSA, TUCUMAN, CATAMARCA, LA_RIOJA, CHACO, CORRIENTES, SANTIAGO_DEL_ESTERO, CORDOBA, SAN_JUAN, MENDOZA, SAN_LUIS, SANTA_FE, ENTRE_RIOS, BUENOS_AIRES, LA_PAMPA, NEUQUEN, RIO_NEGRO, CHUBUT, SANTA_CRUZ, TIERRA_DEL_FUEGO
}
